import type { Incident } from '@/domain/incidents'
import type { CloudService } from '@/domain/readiness'

export const cloudServices: CloudService[] = [
  {
    id: 'identity',
    name: 'Citizen identity gateway',
    owner: 'Platform Auth',
    region: 'de-fra-1',
    status: 'operational',
    availabilityTarget: 99.95,
    availabilityActual: 99.98,
    p95LatencyMs: 182,
    errorRate: 0.04,
    lastDeploy: '2026-06-18T09:20:00.000Z',
    wcagRisk: 'low',
    dependencies: [
      {
        id: 'postgres-auth',
        name: 'Auth PostgreSQL',
        criticality: 'high',
        status: 'operational',
      },
      {
        id: 'email',
        name: 'Transactional email',
        criticality: 'medium',
        status: 'operational',
      },
    ],
  },
  {
    id: 'learning',
    name: 'Education collaboration portal',
    owner: 'Learning Products',
    region: 'de-ber-1',
    status: 'degraded',
    availabilityTarget: 99.9,
    availabilityActual: 99.72,
    p95LatencyMs: 644,
    errorRate: 0.42,
    lastDeploy: '2026-06-20T14:42:00.000Z',
    wcagRisk: 'medium',
    dependencies: [
      {
        id: 'object-storage',
        name: 'Object storage',
        criticality: 'high',
        status: 'degraded',
      },
      { id: 'search', name: 'Search index', criticality: 'medium', status: 'operational' },
    ],
  },
  {
    id: 'research-data',
    name: 'Research data workspace',
    owner: 'Research Cloud',
    region: 'eu-ams-1',
    status: 'maintenance',
    availabilityTarget: 99.8,
    availabilityActual: 99.81,
    p95LatencyMs: 318,
    errorRate: 0.09,
    lastDeploy: '2026-06-16T21:10:00.000Z',
    wcagRisk: 'low',
    dependencies: [
      {
        id: 'archive',
        name: 'Archive cluster',
        criticality: 'medium',
        status: 'maintenance',
      },
      {
        id: 'metrics',
        name: 'Metrics pipeline',
        criticality: 'low',
        status: 'operational',
      },
    ],
  },
  {
    id: 'benefits',
    name: 'Benefits application workflow',
    owner: 'Civic Services',
    region: 'de-fra-1',
    status: 'operational',
    availabilityTarget: 99.9,
    availabilityActual: 99.93,
    p95LatencyMs: 246,
    errorRate: 0.12,
    lastDeploy: '2026-06-19T07:35:00.000Z',
    wcagRisk: 'medium',
    dependencies: [
      { id: 'forms', name: 'Form renderer', criticality: 'high', status: 'operational' },
      {
        id: 'pdf',
        name: 'Document generation',
        criticality: 'medium',
        status: 'operational',
      },
    ],
  },
]

export const incidents: Incident[] = [
  {
    id: 'INC-2481',
    title: 'Object storage latency above education portal threshold',
    serviceId: 'learning',
    region: 'de-ber-1',
    severity: 'sev2',
    openedAt: '2026-06-21T08:12:00.000Z',
    status: 'mitigating',
    customerImpact: 'File previews intermittently exceed agreed response targets.',
    nextAction: 'Shift read traffic to warm replica and validate cache hit rate.',
    runbookUrl: 'https://example.com/runbooks/storage-latency',
  },
  {
    id: 'INC-2474',
    title: 'Archive maintenance validation',
    serviceId: 'research-data',
    region: 'eu-ams-1',
    severity: 'sev3',
    openedAt: '2026-06-20T22:00:00.000Z',
    status: 'monitoring',
    customerImpact: 'Scheduled archive imports are paused for selected institutions.',
    nextAction: 'Confirm checksum report before re-enabling imports.',
    runbookUrl: 'https://example.com/runbooks/archive-maintenance',
  },
]
